#!/bin/sh

### BEGIN INIT INFO
# Provides: god
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5

# Default-Stop: 0 1 6
# Short-Description: God
### END INIT INFO

NAME=god
DESC=god
DEAMON=/usr/bin/god
PID=/var/run/god/god.pid
LOG=/var/log/god.log
GOD_CONFIG=/etc/god/*.god

set -e

# Make sure the binary and the config file are present before proceeding

test -x $DEAMON || exit 0

. /lib/lsb/init-functions

RETVAL=0

[ ! -e '/var/run/god' ] && mkdir -p -m 755 /var/run/god

case "$1" in
start)
echo -n "Starting $DESC: "
$DEAMON -c $GOD_CONFIG -P $PID -l $LOG
RETVAL=$?
echo "$NAME."

;;
stop)
echo -n "Stopping $DESC: "
kill `cat $PID`
RETVAL=$?
echo "$NAME."
;;
restart)
echo -n "Restarting $DESC: "
kill `cat $PID`
$DEAMON -c $GOD_CONFIG -P $PID -l $LOG

RETVAL=$?
echo "$NAME."
;;
status)
$DEAMON status
RETVAL=$?
;;
*)
echo "Usage: god {start|stop|restart|status}"
exit 1
;;
esac

exit $RETVAL
